language: objective-c
cache:
  directories:
  - build
  - vendor
jobs:
  include:
  - stage: build
    osx_image: xcode10.2
    install:
    - bundle install --path=vendor/bundle --binstubs=vendor/bin
    script:
    - bundle exec rake build-for-testing:simulator
  - &test
    stage: 'test (xcode10)'
    osx_image: xcode10.2
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 4s,OS=9.3']"
    after_success:
    - bash <(curl -s https://codecov.io/bash) -f 'coverage.txt'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (12.9-inch),OS=11.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (12.9-inch),OS=11.0']" TESTCASE='MergedCellTests'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (12.9-inch),OS=11.0']" TESTCASE='ScrollTests/testTableViewScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (12.9-inch),OS=11.0']" TESTCASE='ScrollTests/testColumnHeaderViewScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (12.9-inch),OS=11.0']" TESTCASE='ScrollTests/testRowHeaderViewScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (12.9-inch),OS=11.0']" TESTCASE='ScrollTests/testColumnAndRowHeaderViewScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (12.9-inch),OS=11.0']" TESTCASE='ScrollTests/testCircularScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (12.9-inch),OS=11.0']" TESTCASE='SelectionTests'
  - stage: 'test (xcode10.2)'
    osx_image: xcode10.2
    script:
    - bundle exec rake test:simulator DESTINATIONS="['name=iPad Pro (12.9-inch),OS=11.0']"
    after_success:
    - bash <(curl -s https://codecov.io/bash) -f 'coverage.txt'
  - stage: 'test (xcode10.2)'
    osx_image: xcode10.2
    script:
    - bundle exec rake test:simulator DESTINATIONS="['name=iPhone 7,OS=10.3.1']"
    after_success:
    - bash <(curl -s https://codecov.io/bash) -f 'coverage.txt'
  - stage: carthage
    osx_image: xcode10.2
    script:
    - carthage build --no-skip-current
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
branches:
  only:
  - master
skip_cleanup: true
